const colors = {
	powder: {ru: "пудровый", en: "powder", hex: "#FFC6B5"},
	pink: {ru: "розовый", en: "pink", hex: "#ED72AA",},
	violet: {ru: "фиолетовый", en: "violet", hex: "#9063CD",},
	darkblue: {ru: "тёмно-синий", en: "dark blue", hex: "#021455",},
	blue: {ru: "синий", en: "blue", hex: "#0F3296",},
	skyblue: {ru: "голубой", en: "sky blue", hex: "#54AEF2",},
	aqua: {ru: "морской волны", en: "aqua", hex: "#23748C",},
	darkgreen: {ru: "тёмно-зелёный", en: "dark green", hex: "#005801",},
	green: {ru: "зелёный", en: "green", hex: "#1E9A1C",},
	lime: {ru: "салатовый", en: "lime", hex: "#B1EB50",},
	brown: {ru: "коричневый", en: "brown", hex: "#784B26",},
	lightbrown: {ru: "светло-коричневый", en: "light brown", hex: "#AD7D5A",},
	golden: {ru: "золотистый", en: "golden", hex: "#D3AE3B",},
	yellow: {ru: "жёлтый", en: "yellow", hex: "#FDD406",},
	orange: {ru: "оранжевый", en: "orange", hex: "#FF7E3D",},
	red: {ru: "красный", en: "red", hex: "#E23726",},
	darkred: {ru: "тёмно-красный", en: "dark red", hex: "#B00F04",},
	carmine: {ru: "карминовый", en: "carmine", hex: "#8A1538",},
	black: {ru: "чёрный", en: "black", hex: "#000000",},
	darkgrey: {ru: "тёмно-серый", en: "dark grey", hex: "#333333",},
	grey: {ru: "серый", en: "grey", hex: "#CCCCCC",},
	white: {ru: "белый", en: "white", hex: "#FFFFFF",},
};