const flag_colors = {
	"AB": ["golden", "yellow", "skyblue", "green", "black", "white"],
	"AD": ["white", "golden", "red", "yellow", "blue", "brown"],
	"AE": ["darkgreen", "red", "black", "white"],
	"AF": ["white", "black"],
	"AG": ["red", "yellow", "blue", "black", "white"],
	"AH": ["white", "red", "green"],
	"AJ": ["white", "orange", "darkgreen"],
	"AL": ["red", "black"],
	"AM": ["blue", "red", "orange"],
	"AO": ["red", "black", "yellow"],
	"AR": ["golden", "skyblue", "brown", "white"],
	"AT": ["white", "red"],
	"AU": ["white", "darkblue", "red"],
	"AZ": ["red", "skyblue", "green", "white"],
	"BA": ["white", "blue", "yellow"],
	"BB": ["blue", "black", "yellow"],
	"BD": ["red", "darkgreen"],
	"BE": ["red", "black", "yellow"],
	"BF": ["yellow", "red", "green"],
	"BG": ["white", "red", "green"],
	"BH": ["white", "red"],
	"BI": ["white", "red", "green"],
	"BJ": ["yellow", "red", "green"],
	"BN": ["red", "yellow", "black", "white"],
	"BO": ["white", "lightbrown", "darkgreen", "darkgrey", "golden", "red", "grey", "yellow", "skyblue", "green", "darkred", "brown", "black"],
	"BR": ["yellow", "blue", "green", "white"],
	"BS": ["aqua", "black", "yellow"],
	"BT": ["orange", "yellow", "black", "white"],
	"BW": ["skyblue", "white", "black"],
	"BY": ["white", "red", "green"],
	"BZ": ["lightbrown", "darkgreen", "darkgrey", "golden", "red", "grey", "yellow", "skyblue", "blue", "green", "lime", "brown", "black", "white"],
	"CA": ["white", "red"],
	"CD": ["skyblue", "red", "yellow"],
	"CF": ["red", "yellow", "blue", "green", "white"],
	"CG": ["green", "red", "yellow"],
	"CH": ["white", "red"],
	"CI": ["white", "orange", "green"],
	"CK": ["white", "darkblue", "red"],
	"CL": ["white", "blue", "red"],
	"CM": ["yellow", "red", "green"],
	"CN": ["red", "yellow"],
	"CO": ["blue", "red", "yellow"],
	"CR": ["white", "blue", "red"],
	"CU": ["white", "blue", "red"],
	"CV": ["red", "yellow", "blue", "white"],
	"CY": ["white", "orange", "darkgreen"],
	"CZ": ["white", "blue", "red"],
	"DE": ["red", "black", "yellow"],
	"DJ": ["red", "skyblue", "green", "white"],
	"DK": ["darkred", "white"],
	"DM": ["darkgreen", "red", "yellow", "brown", "violet", "black", "white"],
	"DN": ["yellow", "red", "green"],
	"DO": ["darkgreen", "red", "yellow", "darkblue", "green", "black", "white"],
	"DZ": ["white", "red", "darkgreen"],
	"EC": ["white", "aqua", "lightbrown", "darkgreen", "darkgrey", "golden", "red", "grey", "yellow", "skyblue", "blue", "green", "lime", "darkred", "brown", "black"],
	"EE": ["skyblue", "white", "black"],
	"EG": ["golden", "red", "black", "white"],
	"EH": ["red", "green", "black", "white"],
	"ER": ["red", "yellow", "skyblue", "green"],
	"ES": ["white", "golden", "pink", "red", "grey", "yellow", "blue", "green", "black"],
	"ET": ["red", "yellow", "blue", "green"],
	"FI": ["white", "blue"],
	"FJ": ["carmine", "red", "yellow", "skyblue", "darkblue", "green", "black", "white"],
	"FM": ["skyblue", "white"],
	"FR": ["white", "blue", "red"],
	"GA": ["green", "aqua", "yellow"],
	"GB": ["white", "darkblue", "red"],
	"GD": ["red", "yellow", "darkgreen"],
	"GE": ["white", "red"],
	"GH": ["darkgreen", "red", "yellow", "black"],
	"GM": ["red", "blue", "green", "white"],
	"GN": ["green", "red", "yellow"],
	"GQ": ["lightbrown", "red", "grey", "yellow", "skyblue", "green", "brown", "black", "white"],
	"GR": ["white", "blue"],
	"GT": ["darkgreen", "golden", "yellow", "brown", "white", "lightbrown", "yellow", "black", "red", "grey", "skyblue", "green"],
	"GW": ["red", "yellow", "green", "black"],
	"GY": ["red", "yellow", "green", "black", "white"],
	"HN": ["white", "skyblue"],
	"HR": ["red", "yellow", "skyblue", "blue", "black", "white"],
	"HT": ["golden", "red", "yellow", "blue", "green", "black", "white"],
	"HU": ["white", "red", "darkgreen"],
	"ID": ["white", "red"],
	"IE": ["white", "orange", "green"],
	"IL": ["white", "blue"],
	"IN": ["orange", "blue", "green", "white"],
	"IQ": ["darkgreen", "red", "black", "white"],
	"IR": ["white", "red", "green"],
	"IS": ["white", "blue", "red"],
	"IT": ["white", "red", "green"],
	"JM": ["yellow", "black", "green"],
	"JO": ["darkgreen", "red", "black", "white"],
	"JP": ["white", "red"],
	"JS": ["red", "green", "black", "white"],
	"KE": ["darkgreen", "darkred", "black", "white"],
	"KG": ["red", "yellow"],
	"KH": ["red", "blue", "black", "white"],
	"KI": ["white", "yellow", "darkblue", "darkred", "black"],
	"KK": ["white", "red"],
	"KM": ["red", "yellow", "blue", "green", "white"],
	"KN": ["white", "red", "yellow", "green", "black"],
	"KP": ["white", "blue", "red"],
	"KR": ["red", "blue", "black", "white"],
	"KW": ["darkgreen", "red", "black", "white"],
	"KZ": ["skyblue", "yellow"],
	"LA": ["white", "blue", "red"],
	"LB": ["white", "red", "green"],
	"LC": ["yellow", "skyblue", "black", "white"],
	"LI": ["red", "yellow", "blue", "black"],
	"LK": ["orange", "darkgreen", "carmine", "yellow", "black"],
	"LR": ["white", "darkblue", "red"],
	"LS": ["blue", "green", "black", "white"],
	"LT": ["yellow", "red", "green"],
	"LU": ["skyblue", "white", "red"],
	"LV": ["white", "carmine"],
	"LY": ["red", "green", "black", "white"],
	"MA": ["red", "darkgreen"],
	"MC": ["white", "red"],
	"MD": ["lightbrown", "darkgreen", "red", "yellow", "blue", "black"],
	"ME": ["darkgreen", "golden", "red", "blue", "brown"],
	"MG": ["white", "red", "green"],
	"MH": ["white", "blue", "orange"],
	"MK": ["red", "yellow"],
	"ML": ["green", "red", "yellow"],
	"MM": ["red", "yellow", "green", "white"],
	"MN": ["blue", "red", "yellow"],
	"MR": ["yellow", "red", "green"],
	"MT": ["red", "grey", "black", "white"],
	"MU": ["red", "yellow", "darkblue", "green"],
	"MV": ["white", "red", "green"],
	"MW": ["red", "black", "green"],
	"MX": ["aqua", "orange", "lightbrown", "darkgreen", "golden", "pink", "red", "grey", "yellow", "skyblue", "blue", "darkblue", "green", "powder", "brown", "black", "white"],
	"MY": ["red", "yellow", "darkblue", "white"],
	"MZ": ["red", "yellow", "green", "black", "white"],
	"NA": ["red", "yellow", "blue", "green", "white"],
	"NE": ["white", "orange", "green"],
	"NG": ["white", "green"],
	"NI": ["orange", "carmine", "golden", "red", "yellow", "skyblue", "blue", "darkblue", "green", "lime", "violet", "white"],
	"NL": ["white", "blue", "red"],
	"NO": ["darkred", "white", "darkblue"],
	"NP": ["white", "blue", "red"],
	"NR": ["white", "darkblue", "yellow"],
	"NU": ["red", "yellow", "darkblue", "white"],
	"NZ": ["white", "darkblue", "red"],
	"OM": ["white", "red", "green"],
	"OS": ["white", "red", "yellow"],
	"PA": ["white", "darkblue", "red"],
	"PE": ["aqua", "lightbrown", "orange", "golden", "red", "yellow", "green", "lime", "brown", "black", "white"],
	"PG": ["red", "yellow", "black", "white"],
	"PH": ["red", "yellow", "blue", "white"],
	"PK": ["white", "darkgreen"],
	"PL": ["white", "red"],
	"PS": ["red", "green", "black", "white"],
	"PT": ["white", "darkgreen", "red", "yellow", "blue", "black"],
	"PW": ["skyblue", "yellow"],
	"PY": ["red", "yellow", "blue", "green", "black", "white"],
	"QA": ["white", "carmine"],
	"RO": ["blue", "red", "yellow"],
	"RS": ["darkgrey", "red", "yellow", "blue", "white"],
	"RU": ["white", "blue", "red"],
	"RW": ["skyblue", "green", "yellow"],
	"SA": ["white", "darkgreen"],
	"SB": ["darkgreen", "yellow", "blue", "white"],
	"SC": ["red", "yellow", "blue", "green", "white"],
	"SD": ["red", "green", "black", "white"],
	"SE": ["blue", "yellow"],
	"SG": ["white", "red"],
	"SI": ["red", "yellow", "blue", "white"],
	"SK": ["white", "blue", "red"],
	"SL": ["white", "blue", "green"],
	"SM": ["lightbrown", "darkgreen", "golden", "grey", "yellow", "skyblue", "blue", "green", "black", "white"],
	"SN": ["green", "red", "yellow"],
	"SO": ["skyblue", "white"],
	"SR": ["red", "yellow", "green", "white"],
	"SS": ["red", "yellow", "skyblue", "green", "black", "white"],
	"ST": ["red", "yellow", "green", "black"],
	"SV": ["blue", "darkgreen", "darkblue", "green", "skyblue", "lime", "violet", "red", "orange", "yellow", "powder", "black", "white"],
	"SY": ["red", "green", "black", "white"],
	"SZ": ["darkgrey", "grey", "yellow", "blue", "darkred", "black", "white"],
	"TD": ["darkblue", "red", "yellow"],
	"TG": ["red", "yellow", "green", "white"],
	"TH": ["darkred", "white", "darkblue"],
	"TJ": ["darkgreen", "red", "yellow", "white"],
	"TL": ["red", "yellow", "black", "white"],
	"TM": ["red", "yellow", "green", "black", "white"],
	"TN": ["white", "red"],
	"TO": ["white", "red"],
	"TR": ["white", "red"],
	"TT": ["white", "red", "black"],
	"TV": ["red", "yellow", "skyblue", "darkblue", "white"],
	"TW": ["white", "blue", "red"],
	"TZ": ["yellow", "skyblue", "green", "black"],
	"UA": ["blue", "yellow"],
	"UG": ["red", "grey", "yellow", "black", "white"],
	"US": ["white", "darkblue", "red"],
	"UY": ["yellow", "blue", "brown", "white"],
	"UZ": ["aqua", "red", "green", "white"],
	"VA": ["darkgrey", "golden", "red", "grey", "yellow", "black", "white"],
	"VC": ["blue", "green", "yellow"],
	"VE": ["red", "yellow", "blue", "white"],
	"VN": ["red", "yellow"],
	"VU": ["red", "yellow", "green", "black"],
	"WS": ["white", "darkblue", "red"],
	"XK": ["golden", "blue", "white"],
	"YE": ["white", "red", "black"],
	"ZA": ["darkgreen", "red", "yellow", "darkblue", "black", "white"],
	"ZM": ["orange", "red", "green", "black"],
	"ZW": ["white", "red", "yellow", "green", "black"]
}
